### ISSUE TITLE
Python error in 3.0.0

### ISSUE THREAD

**Issue by ItsCubeTime** [leukbaars/DreamUV#18]
https://user-images.githubusercontent.com/20190653/125646285-313bb39c-3016-4b3a-9adf-5fc84bb4318a.mp4
Move:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\addons\DreamUV-master\DUV_UVTranslate.py", line 219, in modal
    bmesh.update_edit_mesh(self.mesh, False, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (3 given)

location: <unknown location>:-1
```
Scale:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\addons\DreamUV-master\DUV_UVScale.py", line 193, in modal
    bmesh.update_edit_mesh(self.mesh, False, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (3 given)

location: <unknown location>:-1
```
Rotate:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\addons\DreamUV-master\DUV_UVRotate.py", line 128, in modal
    bmesh.update_edit_mesh(self.mesh, False, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (3 given)

location: <unknown location>:-1

```
Mirror:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\addons\DreamUV-master\DUV_UVMirror.py", line 61, in execute
    bmesh.update_edit_mesh(mesh, False, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (3 given)

location: <unknown location>:-1

```
Transfer to selection
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\addons\DreamUV-master\DUV_UVTransfer.py", line 14, in execute
    bpy.ops.uv.select_split()
  File "C:\Program Files\Blender Foundation\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot split selection when sync selection is enabled


location: <unknown location>:-1
```

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/136274125-2e9f627d-76fa-44b8-9a4e-d888813a2940.png)

Can confirm, happens in the Blender Master.
