### ISSUE TITLE
Error while trying to unwrap to Hotspot 

### ISSUE THREAD

**Issue by vladikula** [leukbaars/DreamUV#43]
Python: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DreamUV-master\DUV_HotSpot.py", line 500, in execute
    main(context)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DreamUV-master\DUV_HotSpot.py", line 75, in main
    bpy.ops.object.shade_smooth_by_angle(angle=0.523599)
  File "D:\PROGRAMS\BLENDER\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.object.shade_smooth_by_angle" error, could not be found

**Comment by leukbaars** [comment]
Hi, blender made some big changes to how smoothing works in version 4.1, so any version prior is not supported anymore. Looks like you are using 4.0

**Comment by MrBrax** [comment]
i'm using blender 4.3.2, same error

**Comment by MrBrax** [comment]
reinstalled, works now
